name: Update activity log

on:
  schedule:
    # Every 3 days — Pakistan Standard Time
    - cron: "17 9 */3 * *"
      timezone: "Asia/Karachi"

    - cron: "43 11 */3 * *"
      timezone: "Asia/Karachi"

    - cron: "11 14 */3 * *"
      timezone: "Asia/Karachi"

    - cron: "37 16 */3 * *"
      timezone: "Asia/Karachi"

    - cron: "23 19 */3 * *"
      timezone: "Asia/Karachi"

    - cron: "51 21 */3 * *"
      timezone: "Asia/Karachi"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update activity file
        run: |
          echo "- Automated activity update: $(TZ=Asia/Karachi date '+%Y-%m-%d %H:%M:%S PKT')" >> activity-log.md

      - name: Commit update
        run: |
          git config user.name "rummanhassan13"
          git config user.email "rumanhasan919@gmail.com"

          git add activity-log.md
          git commit -m "chore: update activity log"
          git push
